name: qgis
version: 2.18.15
summary: A Free and Open Source Geographic Information System
description: |
  Create, edit, visualise, analyse and publish geospatial information.
  QGIS feels snappy to use and has a pleasing, easy to use graphical user
  interface. It supports a number of raster and vector data formats, with new
  support easily added using the plugin architectur

grade: devel
confinement: strict
architectures: [amd64]

apps:
  qgis:
    command: desktop-launch qgis
    plugs: [home, network, unity7]
    environment:
      GDAL_DATA: $SNAP/usr/share/gdal/1.11

parts:
  qgis:
    source: https://github.com/qgis/QGIS/archive/final-2_18_15.tar.gz
    plugin: cmake
    after: [python-deps, desktop-qt4]
    build-packages:
      - build-essential
      - bison
      - dh-python
      - doxygen
      - flex
      - gdal-bin
      - graphviz
      - grass-dev
      - libexpat1-dev
      - libfcgi-dev
      - libgdal-dev
      - libgeos-dev
      - libgsl-dev
      - libopenscenegraph-dev
      - libosgearth-dev
      - libpq-dev
      - libproj-dev
      - libqca2-dev
      - libqca2-plugin-ossl
      - libqjson-dev
      - libqscintilla2-dev
      - libqt4-dev
      - libqt4-opengl-dev
      - libqtwebkit-dev
      - libqwt5-qt4-dev
      - libspatialindex-dev
      - libspatialite-dev
      - libsqlite3-dev
      - lighttpd
      - locales
      - pkg-config
      - poppler-utils
      - pyqt4-dev-tools
      - pyqt4.qsci-dev
      - python-all-dev
      - python-qt4-dev
      - python-sip-dev
      - qt4-dev-tools
      - qt4-doc-html
      - spawn-fcgi
      - txt2tags
      - xauth
      - xfonts-100dpi
      - xfonts-75dpi
      - xfonts-base
      - xfonts-scalable
      - xvfb
    stage-packages:
      - libqca2-plugin-ossl
      - libqt4-sql-sqlite
    organize:
      usr/lib/x86_64-linux-gnu/qca/crypto/: usr/lib/x86_64-linux-gnu/qt4/plugins/crypto/
    stage:
      - -include/
      - -usr/share/doc

  python-deps:
    plugin: nil
    stage-packages:
      - python-future
      - python-gdal
      - python-mock
      - python-nose2
      - python-psycopg2
      - python-pyspatialite
      - python-qscintilla2
      - python-qt4
      - python-qt4-sql
      - python-sip
      - python-yaml
      - python-dateutil
      - python-httplib2
      - python-jinja2
      - python-markupsafe
      - python-matplotlib
      - python-owslib
      - python-pygments
      - python-pyproj
      - python-requests
      - python-shapely
      - python-six
      - python-tz
